version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5452:5432"

  starbux:
    build: .
    ports:
      - "8080:8080"
    image: "starbux:latest"
    network_mode: "host"