version: '3.1'

services:
  starbux-server:
    container_name: starbux
    build:
      context: docker-starbux
      dockerfile: Dockerfile
    image: starbux:latest
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5452:5432"