version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5452:5432"

  starbux:
    build: .
    image: "starbux:latest"
    hostname: localhost
    ports:
      - "8080:8080"
    environment:
      POSTGRES_JDBC_USER: root
      POSTGRES_JDBC_PASS: root
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/postgres"